#!/bin/bash

count=`ps -ef | grep "python WudaoServer.py" | grep -v "grep" | wc -l`
 
if [ $count == 0 ]; then
    nohup python WudaoServer.py > ./usr/server.log 2>&1 &
    git pull origin master > ./usr/pull.log 2>&1 &
fi

python WudaoCommand.py $*

